<?php

namespace AppBundle\Repository;

/**
 * ConsulationArchiveBlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsulationArchiveBlocRepository extends \Doctrine\ORM\EntityRepository
{
}
