<?php

namespace AppBundle\Repository;

/**
 * ConsultationArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationArchiveRepository extends \Doctrine\ORM\EntityRepository
{
}
