<?php

namespace AppBundle\Repository;

/**
 * ConsultationArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationArchiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function findConsultationsArchive(){
       $qb = $this->createQueryBuilder ('c');
       $result = $qb
           ->where ($qb->expr()->isNotNull('c.nomFichier'))
           ->andWhere('c.etatConsultation = 5')
       ;
       return $result->getQuery ()->getResult ();

    }
}
