---
- hosts: mpe-docker
  remote_user: root
  become: yes
  gather_facts: no

  tasks:
    - name: installation mariadb
      apt:
        update_cache: yes
        name: [
          'mariadb-server'
        ]

    - name: Copy cnf
      copy:
        src: root/.my.cnf
        dest: /root/.my.cnf

    - name: Restart service mariadb, in all cases
      service:
        name: mysql
        state: restarted

    - name: change root password
      command:  mysql -e " UPDATE  mysql.user set host = '%'  WHERE user = 'root'; flush privileges ;"
      ignore_errors: yes

    - name: change root password
      command:  mysql -e " GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'bb' WITH GRANT OPTION;"
      ignore_errors: yes