---

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: docker commit
      raw: " docker commit mpe mpe_image:latest"

    - name: clean orphan images
      raw: "docker image prune -f"
