---
- hosts: mpe
  remote_user: root
  become: yes
  gather_facts: no
  tasks:
    - name: installation common
      apt:
        update_cache: yes
        name: [
          'aptitude',
          'sudo',
          'vim',
          'htop',
          'nmap',
          'curl',
          'net-tools',
          'composer',
          'git',
          'wget',
          'tcpdump'

        ]